version: '3.8'

services:

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - fantasy-network
    volumes:
      - ./frontend:/app
    command: npm run dev

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - fantasy-network
    volumes:
      - ./backend:/app

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fantasyone
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - fantasy-network

volumes:
  mysql-data:

networks:
  fantasy-network:

