version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fantasy
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend_fantasyone
    container_name: springboot_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: ./frontend_react
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
